% Bias correct climate data

% Notes
% - Raw climate data need to be stored in a particular way. The dimensions
%   of the climate variable must be: lon, lat, time. This is the standard
%   used by ECMWF.
% - Note that this assumes station data are in same time zone as gridded
%   climate data.
% - Station data should also cover the same time period as the gridded
%   data, without any missing days. NaNs are allowed though.

%% Add paths 
addpath(genpath('src'))
addpath('C:\Users\McCarthy\Desktop\misc\bias_correction\config')

%% Get config
cfg = config_stlucia_tas();

%% Display progress
disp('Bias correcting climate data')

%% Get info from config file
clim_var_name = cfg.clim_var_name;
clim_var_long_name = cfg.clim_var_long_name;
clim_var_units = cfg.clim_var_units;
qmf_period = cfg.qmf_period;
bias_interp_method = cfg.bias_interp_method;
bc_type = cfg.bc_type;
preserve_trends = cfg.preserve_trends;
trend_window = cfg.trend_window;
agg_method = cfg.agg_method;
file_path_station_coords = cfg.file_path_station_coords;
file_path_station_clim_var = cfg.file_path_station_clim_var;
file_path_raw_data = cfg.file_path_raw_data;
file_path_bc_data = cfg.file_path_bc_data;
file_path_figures = cfg.file_path_figures;

%% Load climate variable at station and coordinates
[station_clim_var,station_coords,station_lat,station_lon,station_time]...
    = loadstationdata(...
    file_path_station_clim_var,file_path_station_coords);

%% Load raw climate data
[raw_clim_var,raw_lon,raw_lat,raw_time]...
    = loadrawdata(...
    file_path_raw_data,clim_var_name);

%% Get trends in raw and station data
if strcmp(preserve_trends,'yes')
    grid_trends...
        = gettrends(...
        raw_clim_var,3,trend_window);
    station_trends...
        = gettrends(...
        station_clim_var{:,:},1,trend_window);
end

%% Detrend raw data
if strcmp(preserve_trends,'yes')
    raw_clim_var...
        = detrend(...
        raw_clim_var,grid_trends,bc_type);
    station_clim_var{:,:}...
        = detrend(...
        station_clim_var{:,:},station_trends,bc_type);
end

%% Get quantile mapping functions
qmfs...
    = getqmfs(...
    station_clim_var,station_coords,station_time,raw_clim_var,raw_lon,...
    raw_lat,raw_time,qmf_period);

%% Correct raw data to make bias corrected data
bc_clim_var...
    = mapquantiles(...
    raw_clim_var,station_lon,station_lat,qmfs,raw_lon,raw_lat,...
    bias_interp_method,bc_type,qmf_period,raw_time);

%% Interpolate station trends to grid
if strcmp(preserve_trends,'yes')  
    grid_trends_interp...
        = interptrends(...
        station_trends,station_coords.lon,station_coords.lat,raw_lon,...
        raw_lat,grid_trends,bc_type);
end

%% Clear raw data to avoid OOM
clear raw_clim_var grid_trends

%% Retrend bias corrected data
if strcmp(preserve_trends,'yes')
    bc_clim_var...
        = retrend(...
        bc_clim_var,grid_trends_interp,bc_type);
end

%% Clear interpolated grid trends and reload raw and station data
clear grid_trends_interp
[raw_clim_var,~,~,~]...
    = loadrawdata(...
    file_path_raw_data,clim_var_name);
[station_clim_var,station_coords,station_lat,station_lon,station_time]...
    = loadstationdata(...
    file_path_station_clim_var,file_path_station_coords);

%% Get raw and bias-corrected climate variables at stations
raw_clim_var_station...
    = gridtostations(...
    raw_clim_var,station_lon,station_lat,raw_lon,raw_lat,...
    station_clim_var);
bc_clim_var_station...
    = gridtostations(...
    bc_clim_var,station_lon,station_lat,raw_lon,raw_lat,station_clim_var);

%% Make yearly versions of those tables
[station_clim_var_yearly,raw_clim_var_station_yearly,...
    bc_clim_var_station_yearly,years]...
    = makeyearlytables(...
    station_clim_var,raw_clim_var_station,bc_clim_var_station,raw_time,...
    agg_method);

%% Get linear trends
[station_trends,raw_trends,bc_trends]...
    = getlineartrends(...
    station_clim_var_yearly,raw_clim_var_station_yearly,...
    bc_clim_var_station_yearly,years);

%% Make diagnostic plots
makeplots(...
    station_clim_var,station_coords,station_time,raw_clim_var_station,...
    bc_clim_var_station,raw_time,station_clim_var_yearly,...
    raw_clim_var_station_yearly,bc_clim_var_station_yearly,years,...
    station_trends,raw_trends,bc_trends,bc_clim_var,raw_lon,raw_lat,...
    file_path_figures,clim_var_name,clim_var_long_name,clim_var_units);

%% Display averages for testing
disp(nanmean(bc_clim_var,'all'));
disp(nanmean(raw_clim_var,'all'));
disp(nanmean(table2array(station_clim_var),'all'));

%% Put bias corrected data in netcdf file
% savebcdata(...
%     bc_clim_var,file_path_raw_data,file_path_bc_data,clim_var_name)

%% Display progress
disp('Bias correction completed')
