% Make diagnostic plots for bias correction
function makeplots(station_clim_var,station_coords,station_time,...
    raw_station_clim_var,bc_station_clim_var,raw_time,...
    station_clim_var_yearly,raw_station_clim_var_yearly,...
    bc_station_clim_var_yearly,years,station_linear_trends,...
    raw_station_linear_trends,bc_station_linear_trends,...
    raw_lon,raw_lat,file_path_figures,clim_var_name,clim_var_long_name,...
    clim_var_units,bc_grid_clim_var_yearly,bc_grid_linear_trends,agg_method)

% Make maps of long-term average and linear trends
plotmaps(raw_lon,raw_lat,bc_grid_clim_var_yearly,...
    bc_grid_linear_trends,file_path_figures,clim_var_name,...
    clim_var_long_name,clim_var_units,agg_method);

% Make scatter plot of linear trends
plottrendcomparison(station_linear_trends,...
    raw_station_linear_trends,bc_station_linear_trends,...
    file_path_figures,clim_var_name,clim_var_long_name,clim_var_units);

% Make quantile-quantile plots for all stations
plotallstationsqq( ...
    station_clim_var,raw_station_clim_var,bc_station_clim_var,...
    station_time,raw_time,file_path_figures,clim_var_name,...
    clim_var_long_name,clim_var_units);

% Make plot of station data availability
plotstationavailability( ...
    station_clim_var,station_coords,station_time,...
    file_path_figures,clim_var_name);

% Make diagnostic plots for each station
plotstationdiagnostics( ...
    station_clim_var,station_coords,station_time,...
    raw_station_clim_var,bc_station_clim_var,raw_time,...
    station_clim_var_yearly,raw_station_clim_var_yearly,...
    bc_station_clim_var_yearly,years,file_path_figures,...
    clim_var_name,clim_var_long_name,clim_var_units);

end